var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                   o        o     xxx           ",
   "                                                   xx    n xx    xx!xx          ",
   "                                     o       xx     xxxxxxxx     x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                           xxx  ",
   "  xxx     o       o                        o      xxxxx                    x x  ",
   "  x x     x   n   x     o                                                    x  ",
   "  x       xxxxxxxxx                      xxxxx                             o x  ",
   "  x                     o                                                    x  ",
   "  x  @                                                           xxxxx       x  ",
   "  xxxxxxxx         xxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "         x!!!!!!!!!x          x!!!x                  x!!!!!x                    ",
   "         x!!!!!!!!!x          x!!!x                  x!!!!!x                    ",
   "         x!!!!!!!!!x          x!!!x                  x!!!!!x                    ",
   "         xxxxxxxxxxx          xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                                                                   x!x  ",
   "                                      x!!xo                                                                  x!x  ",
   "                                      x!!xxxxxxxxxx                                                          x!x  ",
   "                                      xx!!!!!!!!!!xx                                                         x!x  ",
   "                                       xxxxxxxxxx!!x  o                                                      x!x  ",
   "                                                xx!x xx            o   o                        o   o   o   xx!x  ",
   "                                                 x!x  x                                       xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvxxxx     xx     x   x     xx                !!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                            xxxx     xxxx         xxvxxxx       xxxx         xxxx                 ",
   "                                            x  x     x  x                       x  x         x  x                 ",
   "xxxx                                        xx x     x xx                       xx x         x xx                 ",
   "x  x                                           x     x                             xx        x                    ",
   "x xx                                           xx    x                             x         x                    ",
   "x                                              x     x      o  o     x   x         x         x                    ",
   "x               o   o         xxx   xxx        x     x               x   x         x         x                    ",
   "x             xxxxxxxxx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "x            xx       xx        x o x          x    xx               x   x   x               x                    ",
   "x    @       x         x        x   x          x     x               x   x   x               x                    ",
   "x   xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "x   x x      x         x      xxx o xx         x     x               x     o     x x         x                    ",
   "x!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "x!!!x x!!!!!!x         x!!!!!xxx      xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "x!!!x x!!!!!!x         x!!!!!xxxx o                  x!!!!!!xx !                    xx     xx                     ",
   "x!!!x x!!!!!!x         x!!!!!xxxx                 xxxx!!!!xx   !                     xxxxxxx                      ",
   "x!!!x x!!!!!!x         x!!!!!xxxx           n     x!!!!!!xx    !                                                  ",
   "x!!!x x!!!!!!x         x!!!!!!xxxxxxxxxxxxxxxxxxxxx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "x!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                 o          o         x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                 x       xxxxx        x   x           x                    x!!!x                              ",
   "                 x!!!!!!!x            x   x           x                     xxx                               ",
   "                 xxxxxxxxx           xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "     o       o                        x   x    = = = =x  o  o      xxx       xxx                              ",
   "     x    n  x                       xx   xx          x                     x!!!x                             ",
   "     xxxxxxxxx                o   o   x   x           x  x  x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "          x    x             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "          x!!!!x             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "          xxxxxx             xx           xx                                         xxx                      ",
   "  xxxx           x    x       x     x     x                                         x!!!x               xxxx  ",
   "  x  x           x!!!!x       x    xxx    x                                          xxx                x  x  ",
   "  x xx           xxxxxx       x    xxx    xxxxxxx                        xxxxx                          xx x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx       o                     x  ",
   "  x                                o o    x                              x         xxx                o    x  ",
   "  x                o          xx          x                             xxx       x!!!x   o          xx    x  ",
   "  x                x          x    xxx    x                             x x        xxx              xxx    x  ",
   "  x               xx          xxxxxxxxxxxxx  xo  ox    xo  ox    xo   oxx xx                   o   xxxx    x  ",
   "  x      @       xxx          x           x!!x    x!!!!x    x!!!!x    xx   xx                     xxxxx    x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                         o    ",
   "                                                                                                    xxxxxx    ",
   "                          o                                                                         x    x    ",
   "                                                                                             o      x x  x    ",
   "                   xxx                                                                          xxxxx xxxx    ",
   "       !  o  !                                                            o                                   ",
   "       x     x                                                        xxxxx       n    o   xx                 ",
   "       x= o  x            x                                        xxx    xxxxxxxxxxxxxxxxxxx                 ",
   "       x     x                                                  xxx  v                                        ",
   "       !  o  !            o                                  xxx                                              ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                  o                           ",
   "    x n        x                                                                  x                           ",
   "    xxxxxxxxxxxx                                      xx                          v                           ",
   "                   xxx         xxx                                          x          x      o               ",
   "                                                            o               v                 x               ",
   "                          o                               xxx            o                    v               ",
   "              x           x           x                          xx      o                                o   ",
   "             xvx         xvx         xvx                                 x                  x     x   n  ox   ",
   "  o                                                                                               xxxxxxxxx   ",
   "  o                                                              ||                                           ",
   "  xxxxxxxxxxx                                                                          xxx                    ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                                    ",
   "  x         x   x       x   x       x   x                 ||                    xx                            ",
   "  x         xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xxxxxxxxx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
